#! /bin/bash

# Adapted from @erijo's yadm bootstrap script.
# Source: https://github.com/TheLocehiliosan/yadm/blob/3d82aff/contrib/bootstrap/bootstrap-in-dir

set -eu

printf '\n'

echo 'Some bootstrapping steps require sudo. You may be prompted for your password.'
sudo -v

printf '\n'

# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
# execute all executable files (excluding templates and editor backups) in the
# ~/.config/yadm/bootstrap.d directory when run.

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

if [[ ! -d "$BOOTSTRAP_D" ]]; then
	echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
	exit 1
fi

find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
	if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
		if ! "$bootstrap"; then
			echo "Error: bootstrap '$bootstrap' failed" >&2
			exit 1
		fi
	fi
done

echo 'Bootstrapping complete!'
echo "If this is the first time bootstrapping, you should reload your shell: \`exec zsh -l\`"
