#! /bin/bash

set -e

zsh_path='/bin/zsh'

echo "Setting $(whoami)'s shell to zsh..."
if [[ ! -x "$zsh_path" ]]; then
	echo "Could not find $zsh_path. Please install zsh before continuing."
	echo "You can restart the bootstrapping process by adding the \`-f\` flag to the command you ran before."
	exit 1
fi

if [[ "$SHELL" != "$zsh_path" ]]; then
	sudo chsh -s "$zsh_path" "$(whoami)"
	echo "Successfully set $(whoami)'s shell to zsh."
else
	echo "$(whoami)'s shell is already set to zsh. Skipping..."
fi

printf '\n'
