#! /bin/zsh

set -e

source "$HOME/.zshenv"

# Do not checkout these files
ignored=('!README.md' '!LICENSE')

git --git-dir "$YADM_DATA/repo.git" config 'core.sparseCheckout' 'true'
git --git-dir "$YADM_DATA/repo.git" sparse-checkout set '/*' "${ignored[@]}"
