#! /bin/zsh

set -e

source "$HOME/.zshenv"

files=("$HOME/.cache" "$HOME/.local")

# Get all yadm-tracked folders/files in $HOME (non-recursive)
while IFS='' read -r file; do
	files+=("$file")
done < <(git --git-dir "$YADM_DATA/repo.git" ls-tree --name-only HEAD)

chmod -f 'u=rwX,g=,o=' "${files[@]}" 2> /dev/null || true
