#! /bin/zsh

set -e

omz_home="$HOME/.config/oh-my-zsh"

echo 'Installing oh-my-zsh...'
if [[ ! -f "$omz_home/oh-my-zsh.sh" ]]; then
	git clone 'https://github.com/ohmyzsh/ohmyzsh' "$omz_home"
	echo 'Successfully installed oh-my-zsh.'
else
	echo 'oh-my-zsh is already installed. Skipping...'
fi

printf '\n'
