#! /bin/zsh

set -e

if [[ "$(uname -s)" != 'Darwin' ]]; then
	exit 0
fi

apple_silicon_path='/opt/homebrew/bin/brew'
intel_path='/usr/local/bin/brew'

echo 'Installing Homebrew...'
if [[ ! -x "$apple_silicon_path" && ! -x "$intel_path" ]]; then
	NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	echo 'Successfully installed Homebrew.'
else
	echo 'Homebrew is already installed. Skipping...'
fi

printf '\n'
