#! /bin/zsh

set -e

key_path="$HOME/.ssh/id_ed25519"

echo 'Generating ssh key...'
if [[ ! -f "$key_path" ]]; then
	ssh-keygen -t ed25519 -b 256 -N '' -f "$key_path"
	echo 'Successfully generated ssh key.'
else
	echo "SSH key $key_path already exists. Skipping..."
fi

printf '\n'
